### ISSUE TITLE
predictedAddress does not match expected value

### ISSUE THREAD

**Issue by Tiger-tomcat** [thousandetherhomepage/ketherhomepage#106]
predictedAddress does not match expected value, something went wrong: 0x33DEeBF59333ee901a8F0f1c1D7e56ff53B72Fce != 0xB619c30d26D7F17496D030f1387d2876210341Cd
How to create the "flashEscrowInitCode" in netConfig.js?

**Comment by shazow** [comment]
@Tiger-tomcat What are you trying to do?
