### ISSUE TITLE
CSP issues

### ISSUE THREAD

**Issue by mveytsman** [thousandetherhomepage/ketherhomepage#14]
Reported by @jedahan

>so i'm getting this error with beta firefox, and browsing via parity: `Content Security Policy: The page’s settings blocked the loading of a resource at http://127.0.0.1:8545/rpc/ (“connect-src http://*.infura.io http://storage.thousandetherhomepage.com”)`.

**Comment by mveytsman** [comment]
Should we whitelist localhost for RPC?

- [] doublecheck on mist

**Comment by shazow** [comment]
Deployed https://github.com/thousandetherhomepage/ketherhomepage/commit/c0491bd06435a4dfc7da483ab55d28971d427e25

Can you confirm that parity works now?

**Comment by jedahan** [comment]
Works great, thanks @shazow !

**Comment by shazow** [comment]
@jedahan Yay thanks for confirming!
