### ISSUE TITLE
Make all asset paths relative or determined at build-time

### ISSUE THREAD

**Issue by mveytsman** [thousandetherhomepage/ketherhomepage#18]
For hosting on IPFS to work, we can longer load assets like `/build/base.css`, because the site would be accessed on https://gateway.ipfs.io/HASH or http://localhost:8080/ipfs/HASH. Thus all of our css and javascript paths are broken. You can see at https://gateway.ipfs.io/ipfs/QmPaz3xXmdaK3FmRQAQVx8HcshiybNKhnw6Z219uD1tsh1/

We can either make all the paths relative or make the build-dapp step know the hash (which when we use IPNS will be known pre-build)

**Comment by shazow** [comment]
Relative would be fine but it would need to be different for press/faq/etc.

Another option is to set https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base, but I suspect making things relative is better.

**Comment by shazow** [comment]
Actually I have a better idea: Could inject the base in JS if the URL has /ipfs/ in it.

**Comment by mveytsman** [comment]
Oh i started working on switching over to generating the html via templates so we only have to change links in one place.

**Comment by shazow** [comment]
Okely, I'll hand it over to you. How are you doing templates?

**Comment by mveytsman** [comment]
using ejs and html-webpack-plugin (no static generator, just partials) 

I made a new issue, https://github.com/thousandetherhomepage/ketherhomepage/issues/19 when i close that we can come back to this and do relative links or the js trick you suggested

**Comment by shazow** [comment]
Fancy. Cool, have at it. You solution is more useful than the base relative thing anyways.

**Comment by shazow** [comment]
One more thing: The `<h1><a href="/">The Thousand Ether Homepage</a></h1>` in press/faq still breaks.

**Comment by mveytsman** [comment]
oops good catch!
