### ISSUE TITLE
Use `window.ethereum` instead of `window.web3.currentProvider` and call `ethereum.enable()`

### ISSUE THREAD

**Issue by mveytsman** [thousandetherhomepage/ketherhomepage#26]
In order to support [EIP 1102](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md) it It looks like we should call `ethereum.enable()` in order to support privacy mode.

We should also use `window.ethereum` instead of `window.web3.currentProvider` as the second one is legacy, see https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#api-reference.

**Comment by shazow** [comment]
Fixed in #28

**Comment by shazow** [comment]
Er I guess we can keep it open if we want to improve it by having it only enable when it's actually needed (on buy)
