### ISSUE TITLE
NaN pixels sold

### ISSUE THREAD

**Issue by mveytsman** [thousandetherhomepage/ketherhomepage#3]
Sometimes I see "NaN pixels sold" when using MetaMask & Rinkeby

<img width="244" alt="screen shot 2017-09-27 at 9 58 29 pm" src="https://user-images.githubusercontent.com/34720/30947588-326ea1b0-a3d0-11e7-9adf-111d7aff935b.png">

**Comment by shazow** [comment]
Fixed a while ago.
