### ISSUE TITLE
Questions about pixel resale, Metamask.

### ISSUE THREAD

**Issue by mukberty** [thousandetherhomepage/ketherhomepage#33]
1. How can users resell pixels they have purchased here?
2. What part of the code deals with the pricing of pixels, and the Metamask integration ?

Thanks a ton!

**Comment by mukberty** [comment]
1. Is it this [line](https://github.com/thousandetherhomepage/ketherhomepage/blob/487b9bea16a0bdd5d24342b8bdd2d9cebd2d4f91/src/Buy.vue#L46).

**Comment by shazow** [comment]
We did not build a frontend for reselling pixels, but it is implemented as part of the contract. Someone would need to build a frontend to do a resale market using this function call: https://github.com/thousandetherhomepage/ketherhomepage/blob/487b9bea16a0bdd5d24342b8bdd2d9cebd2d4f91/contracts/KetherHomepage.sol#L124

Could probably wrap ad units in an NFT and sell them on pre-existing platforms, too!

**Comment by mukberty** [comment]
Thank you, selling them as NFTs sounds like a good idea.
To setup a clone, how am I supposed to go about editing the wallet addresses ? Am I supposed to edit values [here
](https://github.com/thousandetherhomepage/ketherhomepage/blob/487b9bea16a0bdd5d24342b8bdd2d9cebd2d4f91/contracts/KetherHomepage.sol#L39) and [here](https://github.com/thousandetherhomepage/ketherhomepage/blob/487b9bea16a0bdd5d24342b8bdd2d9cebd2d4f91/contracts/KetherHomepage.sol#L43), or are they stored elsewhere ?

**Comment by mukberty** [comment]
Where and how is the data stored ? https://storage.thousandetherhomepage.com/mainnet.json

**Comment by shazow** [comment]
Sounds like you have it figured out! :)
