### ISSUE TITLE
Data storage, wallet address editing.

### ISSUE THREAD

**Issue by mukberty** [thousandetherhomepage/ketherhomepage#34]
How am I supposed to go about editing the wallet,contract addresses ? Am I supposed to edit values [here
](https://github.com/thousandetherhomepage/ketherhomepage/blob/487b9bea16a0bdd5d24342b8bdd2d9cebd2d4f91/contracts/KetherHomepage.sol#L39)and [here](https://github.com/thousandetherhomepage/ketherhomepage/blob/487b9bea16a0bdd5d24342b8bdd2d9cebd2d4f91/contracts/KetherHomepage.sol#L43) or [here](https://github.com/thousandetherhomepage/ketherhomepage/blob/487b9bea16a0bdd5d24342b8bdd2d9cebd2d4f91/scripts/withdraw.js#L8) or [here](https://github.com/thousandetherhomepage/ketherhomepage/blob/487b9bea16a0bdd5d24342b8bdd2d9cebd2d4f91/migrations/2_deploy_contracts.js#L8) or are they stored elsewhere ? I couldn't find any keys in `truffle.js` also.

Where and how is the data (pixel ownership, image, link etc.) stored ? https://storage.thousandetherhomepage.com/mainnet.json
How has this been implemented ?

Thanks again.

**Comment by shazow** [comment]
Yea, you're on the right track.

You can certainly deploy your own fork on this project, but it wasn't really designed and documented as a starter project for people to replicate without any solidity experience. So a little bit of digging is required. :)
