### ISSUE TITLE
Corner bug with pixel selector

### ISSUE THREAD

**Issue by purplecones** [thousandetherhomepage/ketherhomepage#4]
![2017-10-03 15 14 42](https://user-images.githubusercontent.com/136654/31144117-b390cd14-a84d-11e7-9c47-0ecd7f3281d4.gif)

**Comment by purplecones** [comment]
Unable to select space adjacent to the tiny square in the corner.

**Comment by shazow** [comment]
Huh weeeeird! I'm going to look into this. Thank you!
