### ISSUE TITLE
Getting buyer address

### ISSUE THREAD

**Issue by mukberty** [thousandetherhomepage/ketherhomepage#41]
What does `ketherhomepage.js` look like in production? 
```
contract('KetherHomepage', function(accounts) {
  const owner = accounts[0]; // this is the account we deploy as owner, see 2_deploy_contracts.js
  const withdrawWallet = accounts[1];
  const account1 = accounts[2];
  const account2 = accounts[3];

  web3.eth.sendTransaction({from:owner, to:account1, value: 10000000000000000000 }, function(err, r) { /* NOP */ });
```
`accounts[2]` and `accounts[3]` are supposed to be test accounts with test-ether while testing, right? So how do you get the address of the buyer in production?

Thanks again.

**Comment by shazow** [comment]
@mukberty Are you referring to the tests?

I think you're looking for https://github.com/thousandetherhomepage/ketherhomepage/blob/master/migrations/2_deploy_contracts.js

Some variables are also passed in through truffle (such as which network).

There's some hints about how we run it here: https://github.com/thousandetherhomepage/ketherhomepage/blob/master/Makefile#L17

Keep in mind, this code is several years old, so the latest truffle etc might have a different API.

**Comment by mukberty** [comment]
@shazow thank you, but what I am trying to understand is how you get the addresses of the pixel buyers in production i.e when network is live. If I am not wrong, the above code is for testing with test-accounts (`accounts[2]` and `accounts[3]`) and using their addresses in the script.

Thank you.

**Comment by shazow** [comment]
Ah! We get the buyer address from the contract metadata.

Here's where we grab the contract metadata: https://github.com/thousandetherhomepage/ketherhomepage/blob/903a5b0e54a3801188be2306dd3f2e8f701deeb8/src/Homepage.vue#L69

Here's where we convert the metadata into our internal representation: https://github.com/thousandetherhomepage/ketherhomepage/blob/903a5b0e54a3801188be2306dd3f2e8f701deeb8/src/store/store.js#L114
