### ISSUE TITLE
Using BSC instead of Mainnet ?

### ISSUE THREAD

**Issue by jesterxd** [thousandetherhomepage/ketherhomepage#62]
I have deployed a contract to BSC, have changed the contract addresses, and replaced the Infura URLs with other providers. Yet, the adgrid doesn't load. What other changes do I have to make ? 
Is this even possible? Will the dApp work with BSC ?

Thank you.

**Comment by shazow** [comment]
I don't know, I don't build on BSC. Let me know when you find out!
