### ISSUE TITLE
Cross-site Scripting (XSS) Issue in Ad Links

### ISSUE THREAD

**Issue by mandatoryprogrammer** [thousandetherhomepage/ketherhomepage#7]
Just a heads up there's an XSS vulnerability in this script, specifically here:
https://github.com/thousandetherhomepage/ketherhomepage/blob/master/src/Ad.vue#L45

Changing:
```js
    link() {
      if (!this.shown) return "";
      if (this.ad.link && this.ad.link.startsWith('javascript:')) return "";
      return this.ad.link;
    },
```

To this:
```js
    link() {
      if (!this.shown) return "";
      if (this.ad.link && this.ad.link.toLowerCase().startsWith('javascript:')) return "";
      return this.ad.link;
    },
```

Should fix this problem! Let me know if you'd like me to do a pull request with a fix.

More info here: https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)

**Comment by mandatoryprogrammer** [comment]
Also since this page is pretty small it may be beneficial to implement Content Security Policy as well:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Might save you from anything I've missed :) cool project idea by the way.

**Comment by mveytsman** [comment]
Thank you for this @mandatoryprogrammer !!

I just implemented and deployed the stopgap. Currently looking into adding CSP. We're doing this through github pages / cloudflare, so I believe META tags is the best way to go: http://qszhuan.github.io/technology/2015/08/12/add_csp_to_github_blog

**Comment by Prinzhorn** [comment]
Might also want to throw some `.trim()` in there, as " javascript:" works as well (note the leading whitespace). Or just use a white-list for http(s) as there are other potentially malicious schemes as well, e.g. "data:".

**Comment by mandatoryprogrammer** [comment]
Ah that's a great point, I gotta stop writing patches so early in the morning :).

**Comment by mveytsman** [comment]
@Prinzhorn we want to support `data:`  urls for images so that you can encode an image directly on the blockchain. Do you know of any issues with using them for image source?

**Comment by mveytsman** [comment]
There's a tension here because with my security hat on I am thinking we should whitelist and never blacklist BUT whitelists limit interesting use cases we aren't thinking of (i.e. opening up magnet links, or bitcoin addresses, etc). We're limiting the non-malicious cool things our users can do with a whitelist.

For now I'm going to blacklist javascript and data when trimmed and lowered, but I'm open to suggestions / feedback!

**Comment by Prinzhorn** [comment]
@mveytsman I'm not aware of any issues with `data:` URIs when used as a `src` of an `<img>`. I was only worried about `href`.

**Comment by shazow** [comment]
Ok, latest setup and CSP succssfully prevents inline javascript like this. We'll keep the extra blacklist layer, too.

**Comment by mveytsman** [comment]
I think we're good for now. I would prefer a whitelist eventually but I can live this until proven otherwise
