### ISSUE TITLE
Update preview image for sharing on social media

### ISSUE THREAD

**Issue by hyfen** [thousandetherhomepage/ketherhomepage#71]
The image used for shares on social media is outdated. 

The `og:image` tag points to https://storage.thousandetherhomepage.com/mainnet.png which is an outdated rendering of the homepage.

**Comment by mveytsman** [comment]
Fixed.

See https://github.com/thousandetherhomepage/ketherstatic/pull/19 

We need to deploy this to run continuously (see https://github.com/thousandetherhomepage/ketherstatic/issues/20)
