### ISSUE TITLE
Add press page

### ISSUE THREAD

**Issue by shazow** [thousandetherhomepage/ketherhomepage#8]
## Posts
- https://news.ycombinator.com/item?id=15393446 ~18K views
- https://www.producthunt.com/posts/the-thousand-ether-homepage ~4.2K views
- http://www.newsbtc.com/2017/10/05/million-dollar-homepage-reborn-ethereum-smart-contract-dapp/

## Random threads 
- [reddit.com/r/Buttcoin](https://www.reddit.com/r/Buttcoin/comments/74253y/meth_huffer_wonders_how_to_create_a_directory_of/) "At least it seems to be completely legal." 😂 
- https://beta.cent.co/question/236

## Noteworthy tweets
- https://twitter.com/malgorithms/status/915263129231097857
- https://twitter.com/balajis/status/916165904253149184

Must construct additional press.

**Comment by shazow** [comment]
Maybe should just make this a Github wiki and link to that.

**Comment by shazow** [comment]
Also we should repost it on steemit next week.

**Comment by mveytsman** [comment]
added (https://thousandetherhomepage.com/press)
