### ISSUE TITLE
netlify: silence "Insecure mixed content detected in"

### ISSUE THREAD

**Issue by shazow** [thousandetherhomepage/ketherhomepage#88]
@mveytsman Could try adding `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` or equivalent to our CSP, might do the trick and/or break things?

**Comment by mveytsman** [comment]
can we get away with the html tag or do we need to mess with the nuxt CSP hell?

**Comment by shazow** [comment]
🤷
