### ISSUE TITLE
component/Ad: Tweak image rendering CSS?

### ISSUE THREAD

**Issue by shazow** [thousandetherhomepage/ketherhomepage#91]
Try `image-rendering: pixelated;` for example?

![image](https://user-images.githubusercontent.com/6292/133175636-ebae1bc3-6d3f-4fbe-a429-918cc01b1f06.png)

**Comment by e1ghtSpace** [comment]
Try this:
`image-rendering: optimizeSpeed;             /* STOP SMOOTHING, GIVE ME SPEED  */`
`image-rendering: -moz-crisp-edges;          /* Firefox                        */`
`image-rendering: -o-crisp-edges;            /* Opera                          */`
`image-rendering: -webkit-optimize-contrast; /* Chrome (and eventually Safari) */`
`image-rendering: pixelated; /* Chrome */`
`image-rendering: optimize-contrast;         /* CSS3 Proposed                  */`
`-ms-interpolation-mode: nearest-neighbor;   /* IE8+                           */`

Taken from https://stackoverflow.com/questions/14068103/disable-antialising-when-scaling-images

**Comment by shazow** [comment]
@e1ghtSpace :pray:

**Comment by e1ghtSpace** [comment]
![image](https://user-images.githubusercontent.com/7877659/133179322-1a70a5de-a761-4049-972a-2f9d93a4569d.png)

I think this is right? I tried to make a branch and do a pull request but I don't have permission. :(
I also have no idea how to test this anyway, so its probably good that I couldn't . :)
